In [2]:
# import packages
import pandas as pd
import numpy as np

In [3]:
# load file
df = pd.read_csv("/home/thuy/Documents/Data Science/02. DS4A/Capstone_teamrepo/DS4A-TeamProject/data/Pre-merging/Opioid_Deaths_by_County_2015-2020.csv")
df.head()

      County  Rates  Counts  Year
0    Alameda   3.82    68.0  2015
1     Alpine   0.00     0.0  2015
2     Amador   3.75     2.0  2015
3      Butte   7.48    18.0  2015
4  Calaveras  17.97     9.0  2015

In [4]:
# remove California total number and Unknown
df = df[df["County"] != "California"]
df = df[df["County"] != "Unknown"]
df["County"].unique()

array(['Alameda', 'Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa',
       'Contra Costa', 'Del Norte', 'El Dorado', 'Fresno', 'Glenn',
       'Humboldt', 'Imperial', 'Inyo', 'Kern', 'Kings', 'Lake', 'Lassen',
       'Los Angeles', 'Madera', 'Marin', 'Mariposa', 'Mendocino',
       'Merced', 'Modoc', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Orange',
       'Placer', 'Plumas', 'Riverside', 'Sacramento', 'San Benito',
       'San Bernardino', 'San Diego', 'San Francisco', 'San Joaquin',
       'San Luis Obispo', 'San Mateo', 'Santa Barbara', 'Santa Clara',
       'Santa Cruz', 'Shasta', 'Sierra', 'Siskiyou', 'Solano', 'Sonoma',
       'Stanislaus', 'Sutter', 'Tehama', 'Trinity', 'Tulare', 'Tuolumne',
       'Ventura', 'Yolo', 'Yuba'], dtype=object)

In [5]:
# check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 348 entries, 0 to 359
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   County  348 non-null    object
 1   Rates   348 non-null    float64
 2   Counts  348 non-null    float64
 3   Year    348 non-null    int64
dtypes: float64(2), int64(1), object(1)
memory usage: 13.6+ KB

In [6]:
# make sure County names don't have space (prepare for joining)
df["County"] = df["County"].str.strip()

In [7]:
# divide the rates and counts into precovid and covid
precovid_df = df[df["Year"] != 2020]
precovid_df["Year"].value_counts()

2015    58
2016    58
2017    58
2018    58
2019    58
Name: Year, dtype: int64

In [8]:
precovid_county = precovid_df.groupby("County")[["Rates","Counts"]].mean()
precovid_county

                  Rates  Counts
County
Alameda           3.502    63.0
Alpine            0.000     0.0
Amador            6.556     3.0
Butte             6.900    16.2
Calaveras        10.566     4.6
Colusa            4.492     1.0
Contra Costa      5.520    65.4
Del Norte         7.690     2.2
El Dorado         4.502     7.8
Fresno            5.406    52.4
Glenn             2.800     0.8
Humboldt         18.330    25.4
Imperial          8.332    13.6
Inyo             11.668     1.8
Kern              9.258    82.6
Kings             3.148     4.6
Lake             22.304    17.2
Lassen           15.930     5.4
Los Angeles       4.236   457.4
Madera            5.650     9.2
Marin             5.432    12.4
Mariposa          7.138     1.4
Mendocino        17.310    15.6
Merced            7.576    19.2
Modoc             6.148     0.8
Mono              1.378     0.2
Monterey          2.698    12.2
Napa              3.384     4.8
Nevada            7.228     7.0
Orange            7.790   263.8
Placer            4.362    17.0
Plumas           12.636     1.8
Riverside         6.270   155.6
Sacramento        4.326    69.0
San Benito        5.950     3.6
San Bernardino    3.386    74.0
San Diego         7.632   273.4
San Francisco    14.070   142.8
San Joaquin       6.174    46.6
San Luis Obispo   7.398    20.8
San Mateo         4.592    38.0
Santa Barbara     7.038    31.4
Santa Clara       3.310    69.8
Santa Cruz        9.710    26.8
Shasta            9.642    16.8
Sierra            0.000     0.0
Siskiyou         11.772     5.2
Solano            4.356    19.6
Sonoma            7.986    40.0
Stanislaus        5.170    28.4
Sutter            3.526     3.4
Tehama            2.142     1.6
Trinity          10.362     1.8
Tulare            2.470    11.0
Tuolumne         10.522     6.0
Ventura           8.328    73.2
Yolo              4.014     8.6
Yuba              8.710     6.0

In [9]:
# During COVID
covid_county = df[df["Year"] == 2020]
covid_county

              County  Rates  Counts  Year
300          Alameda   8.09   144.0  2020
301           Alpine   0.00     0.0  2020
302           Amador  13.07     4.0  2020
303            Butte  11.54    26.0  2020
304        Calaveras   7.00     2.0  2020
306           Colusa  14.72     3.0  2020
307     Contra Costa  12.61   144.0  2020
308        Del Norte   9.01     3.0  2020
309        El Dorado  11.72    22.0  2020
310           Fresno   7.01    71.0  2020
311            Glenn  14.87     3.0  2020
312         Humboldt  18.34    24.0  2020
313         Imperial  19.07    32.0  2020
314             Inyo  22.03     3.0  2020
315             Kern  24.32   222.0  2020
316            Kings   7.36    10.0  2020
317             Lake  26.11    17.0  2020
318           Lassen  18.12     7.0  2020
319      Los Angeles  12.40  1300.0  2020
320           Madera   4.87     7.0  2020
321            Marin  14.06    33.0  2020
322         Mariposa   3.87     1.0  2020
323        Mendocino  25.84    20.0  2020
324           Merced   9.98    29.0  2020
325            Modoc   0.00     0.0  2020
326             Mono   0.00     0.0  2020
327         Monterey   5.85    25.0  2020
328             Napa   5.20     8.0  2020
329           Nevada  34.09    30.0  2020
330           Orange  15.45   503.0  2020
331           Placer  12.22    45.0  2020
332           Plumas   6.28     1.0  2020
333        Riverside  16.05   400.0  2020
334       Sacramento   6.81   107.0  2020
335       San Benito   6.33     4.0  2020
336   San Bernardino  12.95   288.0  2020
337        San Diego  15.14   528.0  2020
338    San Francisco  44.51   443.0  2020
339      San Joaquin  11.10    85.0  2020
340  San Luis Obispo  20.56    57.0  2020
341        San Mateo  10.06    81.0  2020
342    Santa Barbara   3.54    16.0  2020
343      Santa Clara   7.10   143.0  2020
344       Santa Cruz   9.65    26.0  2020
345           Shasta  16.25    27.0  2020
346           Sierra   0.00     0.0  2020
347         Siskiyou  19.37     7.0  2020
348           Solano   8.71    39.0  2020
349           Sonoma  23.69   111.0  2020
350       Stanislaus  13.50    74.0  2020
351           Sutter  10.35    11.0  2020
352           Tehama   3.38     2.0  2020
353          Trinity   0.00     0.0  2020
354           Tulare   8.22    39.0  2020
355         Tuolumne   3.48     2.0  2020
357          Ventura  17.07   141.0  2020
358             Yolo   4.04    10.0  2020
359             Yuba  10.64     9.0  2020

In [10]:
# Join 2 dataframes
county_df = precovid_county.join(covid_county.set_index("County"),lsuffix="_precovid", rsuffix="_covid")

In [11]:
county_df = county_df.drop(columns="Year")
county_df.head()

           Rates_precovid  Counts_precovid  Rates_covid  Counts_covid
County
Alameda             3.502             63.0         8.09         144.0
Alpine              0.000              0.0         0.00           0.0
Amador              6.556              3.0        13.07           4.0
Butte               6.900             16.2        11.54          26.0
Calaveras          10.566              4.6         7.00           2.0

In [12]:
# Rename columns
county_df = county_df.rename(columns=
{"Rates_precovid":"PRECOVID_RATES",
"Counts_precovid":"PRECOVID_COUNTS",
"Rates_covid":"COVID_RATES",
"Counts_covid":"COVID_COUNTS"})
county_df.head()

           PRECOVID_RATES  PRECOVID_COUNTS  COVID_RATES  COVID_COUNTS
County
Alameda             3.502             63.0         8.09         144.0
Alpine              0.000              0.0         0.00           0.0
Amador              6.556              3.0        13.07           4.0
Butte               6.900             16.2        11.54          26.0
Calaveras          10.566              4.6         7.00           2.0

In [13]:
# load hospital-related metrics
facility_df = pd.read_csv("/home/thuy/Documents/Data Science/02. DS4A/Capstone_teamrepo/DS4A-TeamProject/data/Merged_deaths_hospital_availability_by_county.csv")
facility_df.head()

,Unnamed: 0,TOTAL_FAC,TOTAL_NUMBER_BEDS,COUNT_NOER_FAC,COUNT_ER_FAC,ER_BEDS,TOTALFAC_PER_POP,TOTALBEDS_PER_POP,ERFAC_PER_POP,ERBEDS_PER_POP,ERFAC_PER_AREA,COUNTY,DEATHRATES19,DEATHCOUNTS19,DEATHRATES20,DEATHCOUNTS20,COUNTS_GR19,COUNTS_GR20
0,0,3781,65542,3708,72,20947,37.925635,657.424487,0.722202,210.110627,0.017742,Los Angeles,6.70,707.0,12.40,1300.0,42.253521,83.875530
1,1,483,10940,464,19,4079,21.887391,495.751671,0.860995,184.841962,0.000947,San Bernardino,6.10,133.0,12.95,288.0,25.471698,116.541353
2,2,482,14362,456,26,5968,15.180481,452.327936,0.818864,187.960808,0.032878,Orange,8.13,272.0,15.45,503.0,7.936508,84.926471
3,3,421,16456,403,18,6260,12.577414,491.624518,0.537752,187.018077,0.004279,San Diego,8.92,314.0,15.14,528.0,17.164179,68.152866
4,4,340,9074,327,13,2894,20.232315,539.964772,0.773588,172.212701,0.017589,Alameda,5.75,103.0,8.09,144.0,83.928571,39.805825

In [14]:
# join with pre and during covid data
county_merged = county_df.join(facility_df.set_index("COUNTY"))

In [15]:
county_merged.head()

,PRECOVID_RATES,PRECOVID_COUNTS,COVID_RATES,COVID_COUNTS,Unnamed: 0,TOTAL_FAC,TOTAL_NUMBER_BEDS,COUNT_NOER_FAC,COUNT_ER_FAC,ER_BEDS,...,TOTALBEDS_PER_POP,ERFAC_PER_POP,ERBEDS_PER_POP,ERFAC_PER_AREA,DEATHRATES19,DEATHCOUNTS19,DEATHRATES20,DEATHCOUNTS20,COUNTS_GR19,COUNTS_GR20
County,,,,,,,,,,,,,,,,,,,,,
Alameda,3.502,63.0,8.09,144.0,4.0,340.0,9074.0,327.0,13.0,2894.0,...,539.964772,0.773588,172.212701,0.017589,5.75,103.0,8.09,144.0,83.928571,39.805825
Alpine,0.000,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amador,6.556,3.0,13.07,4.0,49.0,5.0,251.0,4.0,1.0,52.0,...,620.580527,2.472432,128.566484,0.001682,7.81,5.0,13.07,4.0,400.000000,-20.000000
Butte,6.900,16.2,11.54,26.0,24.0,44.0,1387.0,41.0,3.0,467.0,...,704.490045,1.523771,237.200325,0.001833,5.83,12.0,11.54,26.0,-29.411765,116.666667
Calaveras,10.566,4.6,7.00,2.0,51.0,5.0,124.0,4.0,1.0,25.0,...,267.708716,2.158941,53.973531,0.000980,7.79,4.0,7.00,2.0,33.333333,-50.000000

In [16]:
# remove unnecessary columns
county_merged = county_merged.drop(columns=["Unnamed: 0","DEATHRATES19","DEATHCOUNTS19","DEATHRATES20","DEATHCOUNTS20","COUNTS_GR19","COUNTS_GR20"])
county_merged.head()

,PRECOVID_RATES,PRECOVID_COUNTS,COVID_RATES,COVID_COUNTS,TOTAL_FAC,TOTAL_NUMBER_BEDS,COUNT_NOER_FAC,COUNT_ER_FAC,ER_BEDS,TOTALFAC_PER_POP,TOTALBEDS_PER_POP,ERFAC_PER_POP,ERBEDS_PER_POP,ERFAC_PER_AREA
County,,,,,,,,,,,,,,
Alameda,3.502,63.0,8.09,144.0,340.0,9074.0,327.0,13.0,2894.0,20.232315,539.964772,0.773588,172.212701,0.017589
Alpine,0.000,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amador,6.556,3.0,13.07,4.0,5.0,251.0,4.0,1.0,52.0,12.362162,620.580527,2.472432,128.566484,0.001682
Butte,6.900,16.2,11.54,26.0,44.0,1387.0,41.0,3.0,467.0,22.348639,704.490045,1.523771,237.200325,0.001833
Calaveras,10.566,4.6,7.00,2.0,5.0,124.0,4.0,1.0,25.0,10.794706,267.708716,2.158941,53.973531,0.000980

In [17]:
county_merged = county_merged.reset_index().rename(columns={"County":"COUNTY"})

In [18]:
county_merged = county_merged.fillna(0)
county_merged

,COUNTY,PRECOVID_RATES,PRECOVID_COUNTS,COVID_RATES,COVID_COUNTS,TOTAL_FAC,TOTAL_NUMBER_BEDS,COUNT_NOER_FAC,COUNT_ER_FAC,ER_BEDS,TOTALFAC_PER_POP,TOTALBEDS_PER_POP,ERFAC_PER_POP,ERBEDS_PER_POP,ERFAC_PER_AREA
0,Alameda,3.502,63.0,8.09,144.0,340.0,9074.0,327.0,13.0,2894.0,20.232315,539.964772,0.773588,172.212701,0.017589
1,Alpine,0.000,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
2,Amador,6.556,3.0,13.07,4.0,5.0,251.0,4.0,1.0,52.0,12.362162,620.580527,2.472432,128.566484,0.001682
3,Butte,6.900,16.2,11.54,26.0,44.0,1387.0,41.0,3.0,467.0,22.348639,704.490045,1.523771,237.200325,0.001833
4,Calaveras,10.566,4.6,7.00,2.0,5.0,124.0,4.0,1.0,25.0,10.794706,267.708716,2.158941,53.973531,0.000980
5,Colusa,4.492,1.0,14.72,3.0,6.0,147.0,5.0,1.0,48.0,27.516625,674.157303,4.586104,220.132997,0.000869
6,Contra Costa,5.520,65.4,12.61,144.0,140.0,4674.0,132.0,8.0,1666.0,12.073753,403.090881,0.689929,143.677665,0.011069
7,Del Norte,7.690,2.2,9.01,3.0,8.0,148.0,7.0,1.0,49.0,28.616397,529.403348,3.577050,175.275433,0.000994
8,El Dorado,4.502,7.8,11.72,22.0,17.0,518.0,15.0,2.0,236.0,8.627821,262.894786,1.015038,119.774459,0.001171
9,Fresno,5.406,52.4,7.01,71.0,182.0,6579.0,175.0,7.0,1732.0,17.959345,649.200710,0.690744,170.909809,0.001175
10,Glenn,2.800,0.8,14.87,3.0,5.0,123.0,4.0,1.0,47.0,17.096940,420.584715,3.419388,160.711233,0.000761
11,Humboldt,18.330,25.4,18.34,24.0,35.0,760.0,31.0,4.0,268.0,26.083198,566.378013,2.980937,199.722773,0.001121
12,Imperial,8.332,13.6,19.07,32.0,24.0,521.0,22.0,2.0,268.0,13.289110,288.484432,1.107426,148.395063,0.000479
13,Inyo,11.668,1.8,22.03,3.0,5.0,161.0,3.0,2.0,62.0,27.434842,883.401920,10.973937,340.192044,0.000196
14,Kern,9.258,82.6,24.32,222.0,144.0,3751.0,134.0,10.0,1514.0,15.770625,410.802878,1.095182,165.810599,0.001230
15,Kings,3.148,4.6,7.36,10.0,17.0,498.0,16.0,1.0,173.0,10.893525,319.116215,0.640796,110.857641,0.000720
16,Lake,22.304,17.2,26.11,17.0,15.0,332.0,13.0,2.0,62.0,23.247164,514.537226,3.099622,96.088277,0.001592
17,Lassen,15.930,5.4,18.12,7.0,7.0,121.0,6.0,1.0,25.0,22.963619,396.942558,3.280517,82.012925,0.000220
18,Los Angeles,4.236,457.4,12.40,1300.0,3781.0,65542.0,3708.0,72.0,20947.0,37.925635,657.424487,0.722202,210.110627,0.017742
19,Madera,5.650,9.2,4.87,7.0,22.0,862.0,20.0,2.0,464.0,13.904953,544.821353,1.264087,293.268106,0.000936
20,Marin,5.432,12.4,14.06,33.0,45.0,1588.0,42.0,3.0,490.0,17.499242,617.528796,1.166616,190.547299,0.005764
21,Mariposa,7.138,1.4,3.87,1.0,5.0,34.0,4.0,1.0,34.0,29.763676,202.393000,5.952735,202.393000,0.000690
22,Mendocino,17.310,15.6,25.84,20.0,28.0,488.0,25.0,3.0,118.0,32.769618,571.127626,3.511030,138.100533,0.000856
23,Merced,7.576,19.2,9.98,29.0,44.0,1021.0,42.0,2.0,224.0,15.452802,358.575252,0.702400,78.668811,0.001034
24,Modoc,6.148,0.8,0.00,0.0,2.0,105.0,0.0,2.0,105.0,22.413986,1176.734282,22.413986,1176.734282,0.000511
25,Mono,1.378,0.2,0.00,0.0,1.0,17.0,0.0,1.0,17.0,6.884208,117.031530,6.884208,117.031530,0.000328
26,Monterey,2.698,12.2,5.85,25.0,67.0,1760.0,63.0,4.0,766.0,15.427728,405.265691,0.921058,176.382681,0.001219
27,Napa,3.384,4.8,5.20,8.0,24.0,2518.0,22.0,2.0,351.0,17.692070,1856.192962,1.474339,258.746517,0.002672
28,Nevada,7.228,7.0,34.09,30.0,16.0,566.0,14.0,2.0,174.0,15.960259,564.594161,1.995032,173.567816,0.002088
29,Orange,7.790,263.8,15.45,503.0,482.0,14362.0,456.0,26.0,5968.0,15.180481,452.327936,0.818864,187.960808,0.032878
30,Placer,4.362,17.0,12.22,45.0,41.0,1960.0,38.0,3.0,798.0,9.992031,477.667811,0.731124,194.479037,0.002132
31,Plumas,12.636,1.8,6.28,1.0,4.0,78.0,1.0,3.0,78.0,21.120439,411.848566,15.840329,411.848566,0.001175
32,Riverside,6.270,155.6,16.05,400.0,300.0,9170.0,283.0,17.0,3512.0,11.904478,363.880225,0.674587,139.361761,0.002359
33,Sacramento,4.326,69.0,6.81,107.0,211.0,7433.0,203.0,8.0,2935.0,13.365597,470.836395,0.506752,185.914815,0.008291
34,San Benito,5.950,3.6,6.33,4.0,6.0,144.0,5.0,1.0,82.0,9.161704,219.880898,1.526951,125.209956,0.000720
35,San Bernardino,3.386,74.0,12.95,288.0,483.0,10940.0,464.0,19.0,4079.0,21.887391,495.751671,0.860995,184.841962,0.000947
36,San Diego,7.632,273.4,15.14,528.0,421.0,16456.0,403.0,18.0,6260.0,12.577414,491.624518,0.537752,187.018077,0.004279
37,San Francisco,14.070,142.8,44.51,443.0,102.0,5334.0,92.0,10.0,2757.0,11.548194,603.902610,1.132176,312.140888,0.213246
38,San Joaquin,6.174,46.6,11.10,85.0,110.0,3882.0,103.0,7.0,1152.0,14.076180,496.761199,0.895757,147.415997,0.005031
39,San Luis Obispo,7.398,20.8,20.56,57.0,69.0,2554.0,65.0,4.0,449.0,24.413976,903.670942,1.415303,158.867758,0.001212
40,San Mateo,4.592,38.0,10.06,81.0,97.0,2879.0,90.0,7.0,1367.0,12.723698,377.644594,0.918205,179.312317,0.015608
41,Santa Barbara,7.038,31.4,3.54,16.0,78.0,2248.0,73.0,5.0,925.0,17.413163,501.856288,1.116228,206.502254,0.001828
42,Santa Clara,3.310,69.8,7.10,143.0,210.0,9263.0,199.0,11.0,3492.0,10.943884,482.729509,0.573251,181.981156,0.008526
43,Santa Cruz,9.710,26.8,9.65,26.0,27.0,1097.0,25.0,2.0,328.0,9.928040,403.372592,0.735410,120.607302,0.004493
44,Shasta,9.642,16.8,16.25,27.0,41.0,1660.0,38.0,3.0,607.0,22.674232,918.029886,1.659090,335.689241,0.000795
45,Sierra,0.000,0.0,0.00,0.0,2.0,39.0,2.0,0.0,0.0,66.203244,1290.963257,0.000000,0.000000,0.000000
46,Siskiyou,11.772,5.2,19.37,7.0,13.0,126.0,11.0,2.0,61.0,29.873383,289.542018,4.595905,140.175104,0.000319
47,Solano,4.356,19.6,8.71,39.0,56.0,1621.0,51.0,5.0,698.0,12.403678,359.042170,1.107471,154.602983,0.006084
48,Sonoma,7.986,40.0,23.69,111.0,80.0,2399.0,74.0,6.0,713.0,16.470327,493.903920,1.235274,146.791786,0.003807
49,Stanislaus,5.170,28.4,13.50,74.0,91.0,3500.0,86.0,5.0,1209.0,16.374917,629.804509,0.899721,217.552472,0.003345
50,Sutter,3.526,3.4,10.35,11.0,21.0,495.0,21.0,0.0,0.0,21.381227,503.986072,0.000000,0.000000,0.000000
51,Tehama,2.142,1.6,3.38,2.0,9.0,205.0,8.0,1.0,76.0,13.389669,304.986908,1.487741,113.068317,0.000339
52,Trinity,10.362,1.8,0.00,0.0,3.0,48.0,2.0,1.0,48.0,25.595086,409.521372,8.531695,409.521372,0.000315
53,Tulare,2.470,11.0,8.22,39.0,75.0,2966.0,72.0,3.0,710.0,15.977606,631.861050,0.639104,151.254668,0.000622
54,Tuolumne,10.522,6.0,3.48,2.0,12.0,362.0,11.0,1.0,72.0,21.953897,662.275887,1.829491,131.723381,0.000450
55,Ventura,8.328,73.2,17.07,141.0,238.0,3456.0,230.0,8.0,1417.0,28.274966,410.581015,0.950419,168.342968,0.004341
56,Yolo,4.014,8.6,4.04,10.0,21.0,739.0,19.0,2.0,153.0,9.490925,333.990166,0.903898,69.148167,0.001971
57,Yuba,8.710,6.0,10.64,9.0,11.0,307.0,10.0,1.0,221.0,13.598714,379.527754,1.236247,273.210533,0.001582

In [19]:
# save to csv
county_merged.set_index("COUNTY").to_csv("/home/thuy/Documents/Data Science/02. DS4A/Capstone_teamrepo/DS4A-TeamProject/data/Merged_precovid_duringcovid_deaths_and_hospital_metrics.csv")